version: "3"

services:

  postgres:
    container_name: "data-engine_postgres"
    restart: "always"
    image: postgres
    env_file:
      - ./config/postgres.env
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data/
    ports:
      - 54320:5432

  metabase:
    container_name: "data-engine_metabase"
    restart: "always"
    image: metabase/metabase
    env_file:
      - ./config/metabase_database.env
    ports:
      - 3000:3000
    volumes:
      - /HOME/docker/volumes/metabase-data:/metabase-data
    depends_on:
      - postgres
    links:
      - postgres
  
  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
    depends_on:
      - postgres
    links:
      - postgres
  